### PR TITLE
certifi 2022.6.15

### PR DESCRIPTION
**Pull request by skupr-anaconda**
License: https://github.com/certifi/python-certifi/blob/2022.06.15/LICENSE
Changes: https://github.com/certifi/python-certifi/compare/2022.05.18.1...2022.06.15
Requirements: https://github.com/certifi/python-certifi/blob/2022.06.15/setup.py

Actions:
1. Skip py<36
2. Remove python from test/requires

### CODE REVIEW

**Review by cbouss — APPROVED** [review]
LGTM

**Review by varlackc — COMMENTED** [review]
Need Setuptools.
https://github.com/certifi/python-certifi/blob/2022.06.15/setup.py#L13

it is possible that we might need wheel also.
https://github.com/certifi/python-certifi/blob/2022.06.15/setup.py#L29

**Comment by skupr-anaconda** [comment]
> Need Setuptools. https://github.com/certifi/python-certifi/blob/2022.06.15/setup.py#L13
> 
> it is possible that we might need wheel also. https://github.com/certifi/python-certifi/blob/2022.06.15/setup.py#L29

We download setuptools and pip separately to avoid circular dependency https://github.com/AnacondaRecipes/certifi-feedstock/blob/4ba5d6c4019cb9c5eb3288c6912a0b4e98a7c261/recipe/meta.yaml#L14-L21
But wheel we can add

**Comment by skupr-anaconda** [comment]
I've added `wheel`. Without it the logs were:
`Using legacy 'setup.py install' for certifi, since package 'wheel' is not installed.`

**Pull request merged**
